name: admin
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://fnx.io
#author: Vaclav Rasendorfer <rasendorfer@gmail.com>

environment:
  sdk: '2.3.0'

dependencies:
  angular: ^5.3.0
  angular_router: ^2.0.0-alpha+22
  fnx_ui:
    git:
      url: https://github.com/fnx-io/fnx_ui
      path: fnx_ui
      ref: v2
  fnx_rest: ^2.1.1
  logging: "^0.11.3"
  i69n: ^0.0.5

dev_dependencies:
  build_modules: 2.1.2
  package_resolver: 1.0.10
  build_runner: ^1.3.3
  build_web_compilers: any

